"""Initial migration

Revision ID: 39c9e13b6778
Revises: 
Create Date: 2025-05-24 11:43:40.069530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39c9e13b6778'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('passhash', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('flagged', sa.Boolean(), nullable=True),
    sa.Column('user_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investor_type', sa.Enum('investor', name='investor_type_enum'), nullable=False),
    sa.Column('industry', sa.String(length=256), nullable=False),
    sa.Column('overall_budget', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('startup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('startup_type', sa.Enum('startup', name='startup_type_enum'), nullable=False),
    sa.Column('platform', sa.Enum('Website', 'App', 'Both', name='startup_platform_enum'), nullable=False),
    sa.Column('sector', sa.Enum('AI', 'FINTECH', 'EDTECH', 'HEALTHCARE', 'AGRITECH', 'SUSTAINABILITY', 'LOGISTICS', 'ECOMMERCE', name='sectorenum'), nullable=False),
    sa.Column('traction', sa.Integer(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funding_campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sector', sa.Enum('AI', 'FINTECH', 'EDTECH', 'HEALTHCARE', 'AGRITECH', 'SUSTAINABILITY', 'LOGISTICS', 'ECOMMERCE', name='sectorenum'), nullable=False),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('investor_id', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('created_on', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['investor_id'], ['investor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('startup_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('profile_picture', sa.String(length=256), nullable=True),
    sa.Column('earnings', sa.Float(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('valuation', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['startup.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('pitch_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('startup_id', sa.Integer(), nullable=False),
    sa.Column('pitch_text', sa.Text(), nullable=True),
    sa.Column('proposed_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', 'completed', name='pitch_status_enum'), nullable=True),
    sa.Column('created_on', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['funding_campaign.id'], ),
    sa.ForeignKeyConstraint(['startup_id'], ['startup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pitch_request')
    op.drop_table('startup_details')
    op.drop_table('funding_campaign')
    op.drop_table('startup')
    op.drop_table('investor')
    op.drop_table('admin')
    op.drop_table('user')
    # ### end Alembic commands ###
