"""Add flagged column to Investor, Startup, FundingCampaign

Revision ID: e5a449d8aa70
Revises: fcd44a09b311
Create Date: 2025-05-25 11:45:32.125529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5a449d8aa70'
down_revision = 'fcd44a09b311'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funding_campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flagged', sa.Boolean(), nullable=True))

    with op.batch_alter_table('investor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flagged', sa.Boolean(), nullable=True))

    with op.batch_alter_table('startup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flagged', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('startup', schema=None) as batch_op:
        batch_op.drop_column('flagged')

    with op.batch_alter_table('investor', schema=None) as batch_op:
        batch_op.drop_column('flagged')

    with op.batch_alter_table('funding_campaign', schema=None) as batch_op:
        batch_op.drop_column('flagged')

    # ### end Alembic commands ###
