"""Add followers to Influencer

Revision ID: f6d722975dca
Revises: 4b050e9bd37d
Create Date: 2024-07-10 13:16:55.767824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6d722975dca'
down_revision = '4b050e9bd37d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('influencer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('followers', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('influencer', schema=None) as batch_op:
        batch_op.drop_column('followers')

    # ### end Alembic commands ###
