"""Add is_paid to PitchRequest

Revision ID: fcd44a09b311
Revises: 4007477360ad
Create Date: 2025-05-25 11:18:00.625489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcd44a09b311'
down_revision = '4007477360ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pitch_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_paid', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pitch_request', schema=None) as batch_op:
        batch_op.drop_column('is_paid')

    # ### end Alembic commands ###
